site_name: threats

nav:
  - What? Why? How?: "README.md"
  - Threat landscape:
    - Introduction: "backdrop/README.md"
    - Unusual suspects: "backdrop/adversaries.md"
    - Marketplaces: "backdrop/marketplace.md"
    - Red team takeover: "backdrop/c2.md"
    - Malware-as-a-Service (MaaS): "backdrop/maas.md"
    - Ransomware-as-a-Service (RaaS): "backdrop/raas.md"
    - Infostealer-as-a-Service (IaaS): "backdrop/iaas.md"
    - More LOL: "backdrop/lol.md"
    - Botnet activity increase: "backdrop/botnets.md"
    - No device can ever be called secure: "backdrop/youtoo.md"
    - "backdrop/drive-by.md"
    - MFA bypass attacks: "backdrop/mfa.md"
    - Oddly overlooked dependencies?: "backdrop/odd.md"
  - Mobile threats:
    - Introduction: "mobile/README.md"
    - "mobile/malware.md"
    - "mobile/smishing.md"
    - "mobile/vishing.md"
    - "mobile/swapping.md"
    - "mobile/otp-bots.md"
    - "mobile/squatting.md"
    - "mobile/ransomware.md"
    - "mobile/madware.md"
    - "mobile/spyware.md"
    - "mobile/tracking.md"
    - "mobile/stalkerware.md"
  - Mitre Att&Ck:
    - Introduction: "mitre/README.md"
    - Initial access shifts: "mitre/initial.md"
    - Phishing for information: "mitre/phishing.md"
    - Application Layer Protocol (Mail Protocols): "mitre/c2.md"
    - Drive-by compromise: "mitre/drive-by.md"
    - Supply chain compromise: "mitre/supply-chain.md"
    - Signs of a compromise @home: "mitre/iocs.md"
